import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: 'category',
      label: 'Introduction to Cedra',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'intro',
      },
      items: [
        {
          type: 'doc',
          id: 'handbook-for-newcomers',
          label: 'Handbook for Newcomers'
        },
        {
          type: 'doc',
          id: 'architecture',
          label: 'Architecture'
        },
        {
          type: 'doc',
          id: 'full-node',
          label: 'Full Node'
        },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'getting-started/faucet',
          label: 'Faucet'
        },
      ],
    },
    {
      type: 'category',
      label: 'Real World Guides',
      link: {
        type: 'doc',
        id: 'real-world-guides',
      },
      items: [
        {
          type: 'doc',
          id: 'guides/first-fa',
          label: 'Fungible Asset (FA) End-to-End Guide'
        },
        {
          type: 'doc',
          id: 'guides/escrow',
          label: 'From Lockup to Payout: Building Secure FA Escrows WIP'
        }
      ],
    },
  ],
};

export default sidebars;
