import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/index',
      },
      items: [
        {
          type: 'doc',
          id: 'getting-started/cli',
          label: 'CLI Installation'
        },
        {
          type: 'doc',
          id: 'getting-started/faucet',
          label: 'Faucet'
        },
        {
          type: 'doc',
          id: 'getting-started/tx',
          label: 'First Transactions'
        },
        {
          type: 'doc',
          id: 'getting-started/counter',
          label: 'Build a Counter Contract'
        },
      ],
    },
    {
      type: 'category',
      label: 'Move Programming Fundamentals',
      link: {
        type: 'doc',
        id: 'move/index',
      },
      items: [
        {
          type: 'doc',
          id: 'move/introduction',
          label: 'Resource First'
        },
        {
          type: 'doc',
          id: 'move/basics',
          label: 'Basic Syntax and Data Types'
        },
        {
          type: 'doc',
          id: 'move/modules',
          label: 'Dive deep into Move Modules'
        },
        {
          type: 'doc',
          id: 'move/functions',
          label: 'Functions in Move'
        },
        {
          type: 'doc',
          id: 'move/resource',
          label: 'Resource Types'
        },
        {
          type: 'doc',
          id: 'move/ownership',
          label: 'Ownership & Borrowing'
        },
        {
          type: 'doc',
          id: 'move/flow',
          label: 'Conditionals, Loops, and Control Flow'
        },
        {
          type: 'doc',
          id: 'move/errors',
          label: 'Error Handling and Assertions'
        }
      ],
    },
    {
      type: 'category',
      label: 'Introduction to Cedra',
      link: {
        type: 'doc',
        id: 'intro',
      },
      items: [
        {
          type: 'doc',
          id: 'handbook-for-newcomers',
          label: 'Handbook for Newcomers'
        },
        {
          type: 'category',
          label: 'Architecture',
          link: {
            type: 'doc',
            id: 'architecture',
          },
          items: [
            {
              type: 'doc',
              id: 'full-node',
              label: 'Full Node'
            },
          ],
        },
      ],
    },
    
    {
      type: 'doc',
      label: 'CLI Usage',
      id: 'cli/usage',
    },
    {
      type: 'category',
      label: 'Real World Guides',
      link: {
        type: 'doc',
        id: 'real-world-guides',
      },
      items: [
        {
          type: 'doc',
          id: 'guides/first-fa',
          label: 'Fungible Asset (FA) End-to-End Guide'
        },
        {
          type: 'doc',
          id: 'guides/first-nft',
          label: 'NFT Contract - Full Code Walkthrough'
        },
        {
          type: 'doc',
          id: 'guides/fee-splitter',
          label: 'Build a Fee Splitter Contract'
        },
        {
          type: 'doc',
          id: 'guides/escrow',
          label: 'Building Secure Token vesting, Marketplace payments via Escrow'
        }
      ],
    },
    {
      type: 'doc',
      label: 'Glossary', 
      id: 'glossary'
    },
  ],
};

export default sidebars;
